Repository ISISComputingGroup/ibex_gui, pull requests merged in 2019-11, with the labels that each got.

#985 Fix JSON dependency
  base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
Labels: size/S

#986 Removed incorrect json feature
  base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
Labels: size/XS

#988 Be less picky about CS-studio build dates
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/M

#990 Remove accidentally added dependency
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
Labels: size/XS
