Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-10, with the labels that each got.

#1196 Remove height2 for vertical mode. Fix PVs
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/sample_stack.opi
Labels: size/M

#1203 add opis for user buttons
  base/uk.ac.stfc.isis.ibex.opis/resources/instetc/single_button.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/instetc/user_buttons.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1199 Add SANS sample changer opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/XXL

#1200 Ticket5722
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/L

#1173 Ticket 4573: OPI for named aperture and guide positions
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/inout_motion_setpoints.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/linear_sample_changer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/openOPI.py
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sample_changer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/XXL
