Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-03, with the labels that each got.

#1077 Stopping eclipse displaying memory monitor by default
  base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini
Labels: size/XS

#1078 Remove log4j from feature requirements
  base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml
Labels: size/XS

#1079 Add icons dir to build path
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/build.properties
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/pom.xml
Labels: size/XS

#1076 Ticket4871
  base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper.opi
Labels: size/XXL

#1082 Show error log on refl front panel
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
Labels: size/L

#1087 Add microsoft teams connector
  Jenkinsfile
  scriptgeneratorJenkinsfile
Labels: size/M

#1093 Add missing javadoc tests back in
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml
Labels: size/XS

#1091 Copy jre into the build as part of build.bat
  build/build.bat
  build/jenkins_build.bat
Labels: size/S

#1094 Use /MT with robocopy
  build/build_script_generator.bat
  build/jenkins_build_script_generator.bat
Labels: size/S

#1096 Rename STABLE PV to AT_SETPOINT
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller/zero_field_controller_basic_panel.opi
Labels: size/S
