Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-07, with the labels that each got.

#1111 Added SANS2D waveguide OPI
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/aperture.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/setpoints.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/waveguide_aperture_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/waveguide_aperture.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL

#1149 Ticket 4569: Disable advanced view when not in manager mode
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/L

#1142 Hide channel 1 if not present
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics.opi
Labels: size/XXL

#1107 Add opi
  base/uk.ac.stfc.isis.ibex.opis/resources/mecfrf.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1150 Swap target platform order
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1153 Standard IOC prefix for refl
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
Labels: size/XS

#1154 Set size correctly
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank_status.opi
Labels: size/L

#1161 Ticket4583
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/XL

#1130 Ticket5026
  .gitignore
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
  base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionLoader.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.scriptgenerator.client/Application.e4xmi
  base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini
  build/build_script_generator.bat
Labels: size/L
