Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-12, with the labels that each got.

#1218 Ticket 5781: Add option to reapply mode inits on move for reflectometry
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/action_bar.opi
Labels: size/L

#1217 Ticket4987 hrpd in situ dsc
  base/uk.ac.stfc.isis.ibex.opis/resources/hrpd_in_situ_dsc.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1220 OPI for Metrolab_PT2025
  base/uk.ac.stfc.isis.ibex.opis/resources/Metrolab_PT2025.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1221 Ticket5488 bump strip indicators
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/action_bar.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/full_opi.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_activation_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_collimation_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_constants.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_corrections.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_error_log.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_front_panel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_other_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_redefine.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_slit_params.opi
Labels: size/XXL
