Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-09, with the labels that each got.

#1180 show appropriate message and inhibit motion when CAEN PVs are unavail…
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/L

#1182 Minor tweaks
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/XL

#1185 Update py4j
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1184 Add back old opi
  base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper_v1.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1181 updated interval pv names
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/L

#1188 Rearrange imports
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
  build/build_script_generator.bat
Labels: size/S

#1189 Ticket5660 HTS Magnet OPI first steps
  base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1194 Remove min and max OPI fields
  base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
Labels: size/L

#1195 Disable devicescreens.ui tests ref https://github.com/ISISComputingGr…
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
Labels: size/S
