Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-04, with the labels that each got.

#1099 Fix build
  build/build.bat
Labels: size/XS

#1100 Allow ctrl-C in reflectometry perspective
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml
Labels: size/S

#1088 Ticket4935 sans dls saving data
  base/uk.ac.stfc.isis.ibex.opis/resources/lsicorr.opi
Labels: size/M
