Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-01, with the labels that each got.

#1009 Deploy from master
  scriptgeneratorJenkinsfile
Labels: size/XS

#1012 Remove alarm sensitive borders in opi
  base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_pressure.opi
Labels: size/S

#1013 Disable concurrent builds
  Jenkinsfile
Labels: size/XS

#1006 Ticket5009 muon jaws
  base/uk.ac.stfc.isis.ibex.opis/resources/MuonJaws.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1014 Ticket5043
  base/uk.ac.stfc.isis.ibex.opis/resources/genesys.opi
Labels: size/XXL

#1015 Separate out activation of bundle from start of Python process
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/Activator.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/XS

#1018 Fixing build versioning
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.e4.client.product/pom.xml
  base/uk.ac.stfc.isis.scriptgenerator.client.product/pom.xml
  base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml
Labels: size/XS

#1016 Ticket4926 comission ice fridge
  base/uk.ac.stfc.isis.ibex.opis/resources/ICE_fridge/icefrdge.opi
Labels: size/L

#1023 Remove test suite which no longer exists
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
Labels: size/XS

#1022 Add SP:RBVs for Danfysik OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi
Labels: size/XXL

#1026 Update Py4J version
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/S

#1029 plot window to appear in decent size
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
Labels: size/XS

#1031 Add calibration file to calibrated danfysik opi
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
Labels: size/M

#1028 Making sure tests work
  base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/templates/generator_template.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/test_configs/valid_config.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/test_generator.py
Labels: size/S

#1033 Link to shadow instead of github
  base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/matplotlib.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/template.opi
Labels: size/XS

#1034 Dont install genie python this is in the script generator.
  build/install_script_generator.bat
  build/purge_archive_client.py
Labels: size/M

#1035 Fix path
  build/jenkins_build_script_generator.bat
Labels: size/XS

#1037 GUI: Updated heap size 512->1024mb
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
Labels: size/XS
