Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-11, with the labels that each got.

#1201 Add button to reset the device and resend setpoints
  base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
Labels: size/M

#1209 Fix typo in Kepco OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
Labels: size/XS

#1206 Ticket 5661: Hooked up ramping in HTS magnet OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
Labels: size/L

#1210 Correct opi usage of motion setpoints
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/stopMtrFromMtrName.py
Labels: size/M

#1212 minor OPI fixes
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/SURF/important_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/set_instrument_panels.py
Labels: size/L

#1211 Add laser mode to OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/instetc/user_buttons.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/important_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/important_params.opi
Labels: size/XL

#1214 Increase max_array_bytes for POLREF
  base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml
Labels: size/XS

#1208 Ticket 5662: Added selecting calibration file to HTS magnet opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
Labels: size/M

#1204 Selectively hide polarity SP
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi
Labels: size/S
