Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-02, with the labels that each got.

#1040 Remove project file
  base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/.project
Labels: size/M

#1039 Remove debug
  base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/action_loader.py
Labels: size/XS

#1043 Ticket5116 dae spectra plots ns
  base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plot.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plots_mode.py
  base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plots_script.py
Labels: size/L

#1041 Add lakeshore 372 opi
  base/uk.ac.stfc.isis.ibex.opis/resources/lakeshore372.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1046 Add time start and finish printing
  build/install_client.bat
Labels: size/XS

#1051 Bringing xy graph to front to fix, not sure why it works
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi
Labels: size/L

#1054 Ticket4891: Convert utility scripts to Python 3
  Jenkinsfile
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py
  build/build.bat
  build/build_script_generator.bat
  build/check_build.py
  build/check_jenkins_build.py
  build/jenkins_build.bat
  build/jenkins_build_script_generator.bat
Labels: size/L

#1062 Ensure python 3 is set to a default
  build/build.bat
  build/build_script_generator.bat
Labels: size/XS

#1055 Use multi-threaded robocopy where possible
  build/build.bat
  build/copy_python.bat
  build/install_client.bat
  build/jenkins_build.bat
Labels: size/S

#1056 Aded widgets position checking and widget boundaries test
  base/uk.ac.stfc.isis.ibex.opis/check_OPI_format_utils/common.py
  base/uk.ac.stfc.isis.ibex.opis/check_OPI_format_utils/position.py
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py
  base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore460/Lakeshore460.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore460/Lakeshore460_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore460/Lakeshore460_channel_v.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/TDS3000_trace.opi
Labels: size/M

#1061 Clear mvnErr before running maven again
  build/build.bat
Labels: size/XS

#1063 Copy across the right directory during build
  base/uk.ac.stfc.isis.ibex.scriptgenerator/build.properties
Labels: size/XS

#1069 Fix ls372 opi
  base/uk.ac.stfc.isis.ibex.opis/resources/lakeshore372.opi
Labels: size/M

#1070 Ticket 4058 - Removed uneeded method and moved test
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
Labels: size/S
