Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-06, with the labels that each got.

#1108 Ticket5338 add ioc flipprps
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/flipprps.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/flipper.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/flipper_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/L

#1124 Ticket 4559: Added link to gauge in SANS2D vac OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi
Labels: size/M

#1109 Fix refl OPI script
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setPositionMacros.py
Labels: size/XS

#1127 Set Different directory for script generator release build via jenkins
  build/jenkins_build_script_generator.bat
Labels: size/XS

#1134 Ticket5201 alert instrument motor encoder out of sync
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/checkOnOffPresent.py
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/L

#1138 Ticket4577 vacuum tank opi
  base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_level.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
Labels: size/XXL

#1140 Rename APERTURE to SCRAPER
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
Labels: size/XS
