Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-08, with the labels that each got.

#1163 Build and deploy rpm
  base/uk.ac.stfc.isis.ibex.preferences/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java
  build/build.sh
  build/build_rpm.sh
  build/get_python_write_dir.py
  build/ibex-client.spec
  build/jenkins_build.sh
  build/test-rpm-install.sh
Labels: size/M

#1145 Ticket4579 sans2d vacuum tank stop motion
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/aperture.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/setpoints.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/XXL

#1164 Add control for rear detector beam stop strip
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/L

#1160 Front beamstop control and inhibited light
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/L

#1162 Added part of OPI for front detector strip beam stop
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/L

#1166 Remove alarm sensitivity on set points
  base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_temp.opi
Labels: size/XS

#1168 Load scripts from repo fixing bug where we couldn't load them
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
Labels: size/XS

#1169 Tabs for parameter groups
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/hgaps.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/important_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/sample_stack.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/vgaps.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/align_tab.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setPositionMacros.py
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/set_instrument_panels.py
Labels: size/XXL

#1170 Update parameter for height2
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi
Labels: size/XS

#1171 Update opis
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/sample_stack.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/vgaps.opi
Labels: size/M

#1165 Add button action to stop motors
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/XL

#1174 Update orbit dependcy to available one
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1175 Add opi_info.xml checks as part of build
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
  base/uk.ac.stfc.isis.ibex.opis/check_opi_info.py
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/M

#1179 Fix param name
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi
Labels: size/XS

#1167 Add inidcators saying that motion is disabled
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
Labels: size/M

#1172 Positional Error PV Added
  base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi
Labels: size/XS
