Repository ISISComputingGroup/ibex_gui, pull requests merged in 2020-05, with the labels that each got.

#1101 RIKEN front-end indicates problem with DAQmx connection
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_riken_changeover.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/muon_overviews/psu_summary_indicate_changeover.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/muon_overviews/riken_front_end_overview.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/value.opi
Labels: size/XL

#1113 Use robocopy rather than xcopy to install script generator
  build/install_script_generator.bat
Labels: size/XS

#1115 Delete random button
  base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi
Labels: size/M
