Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-06, with the labels that each got.

#1304 Fix getting of branch name to enable gui builds to be deployed
  Jenkinsfile
Labels: size/XS

#1308 Install python 3 instead of python2 in install_client.bat
  build/install_client.bat
Labels: size/XS

#1312 Fix build by adding the correct dependencies
  base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml
  base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml
Labels: size/M

#1305 Ticket6202 afg3021b opi
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/tekafg3xxx.opi
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/function_generator.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/function_generator_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL

#1311 add WISH vacuum PLC OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/wish_vacuum_plc.opi
Labels: size/XL

#1278 hifi main cryomag opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag_advanced.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1316 Update help details
  base/uk.ac.stfc.isis.ibex.ui.help/resources/gethelp.txt
Labels: size/XS
