Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-08, with the labels that each got.

#1320 Updated the Danfysik OPI to handle 9000 series danfysik
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
Labels: size/XXL

#1334 IOC Log: add time to search datetime filter
  base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/SearchControl.java
Labels: size/S

#1336 Script Gen: handle missing notepad++
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorFileHandler.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/dialogs/SaveScriptGeneratorFileMessageDialog.java
Labels: size/M

#1333 Add_mV_tab_EUROTHRM_OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
Labels: size/XXL

#1335 Script Gen: validate global parameters
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java
Labels: size/M

#1337 Validate global parameters individually
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
Labels: size/XS

#1343 renaming labels
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
Labels: size/XS

#1341 Ticket6635
  base/uk.ac.stfc.isis.ibex.opis/resources/sample_stack/SampleStackDiagram.png
  base/uk.ac.stfc.isis.ibex.opis/resources/sample_stack/sample_stack.opi
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/sample_stack.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/sample_stack_tb.png
Labels: size/XL

#1342 Ticket#6696
  base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/GetBanner.java
Labels: size/XS

#1318 Ticket5811 table bug fixing
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ValidityDisplay.java
  base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java
Labels: size/L

#1345 Ticket6229 ibex logo
  base/uk.ac.stfc.isis.ibex.ui.about/src/uk/ac/stfc/isis/ibex/ui/about/AboutDialogBox.java
  base/uk.ac.stfc.isis.ibex.ui.help/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.help/icon/splash200x132.bmp
  base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/ClientAboutDialogBox.java
Labels: size/M
