Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-01, with the labels that each got.

#1233 fixing typo in script definitions dir name
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
Labels: size/XS

#1202 Add CAEN v895 GUI
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENV895_single.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENv895.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1242 Musr thurlby opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/ttiex355p.opi
Labels: size/XXL

#1240 Ticket5949 musr steering
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/musr_steering.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/musr_steering_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL

#1244 Added CAEN power supply status
  base/uk.ac.stfc.isis.ibex.opis/resources/musr_rotation.opi
Labels: size/L

#1247 fix macro propagation in musr steering opi
  base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi
Labels: size/S
