Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-02, with the labels that each got.

#1241 Ticket5958 musr dual itc503
  base/uk.ac.stfc.isis.ibex.opis/resources/itc503/musr_dual_itc503.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1254 Fix typo
  base/uk.ac.stfc.isis.ibex.opis/resources/ilm200/ilm200.opi
Labels: size/XS

#1255 Ticket653 add ioc hifimags
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_system/individual_magnet.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifimags.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1252 Ticket5302
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
  base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/IsisLog.java
  base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/Opi.java
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/M

#1257 Update dependency path after ticket
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1261 danfysik opi: Fix slew rate placement
  base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
Labels: size/XS
