Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-04, with the labels that each got.

#1275 Ticket6221
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_system/individual_magnet.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifimags.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1279 musr_rotation.opi: Add buttons to turn all psus on/off
  base/uk.ac.stfc.isis.ibex.opis/resources/musr_rotation.opi
Labels: size/L

#1283 Fix placing to remove scrollbar
  base/uk.ac.stfc.isis.ibex.opis/resources/ttiex355p.opi
Labels: size/XL

#1280 Ticket6133 musr steering save
  base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi
Labels: size/L

#1282 Fixed open OPI script to pass through PV prefix
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/openOPI.py
Labels: size/S

#1284 change capitalisation - two temperature controllers were showing up i…
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1285 rename live view to detector live view
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1281 Ticket 6392: Rename select changer to select rack
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/XL

#1286 Ticket6409 select any position
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/XL

#1289 Tidy up some minor requests from scientists
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/L
