Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-07, with the labels that each got.

#1323 Correct broken links and link to higher page
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
  base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini
Labels: size/XS

#1332 Fix script gen build
  base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml
Labels: size/M

#1330 setting from_ibex env var instead of variable in genie python startup
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java
Labels: size/M

#1309 Ticket6370 GUI dep update
  base/uk.ac.stfc.isis.ibex.activemq/.classpath
  base/uk.ac.stfc.isis.ibex.activemq/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.databases/.classpath
  base/uk.ac.stfc.isis.ibex.databases/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.databases/lib/mysql-connector-java-8.0.21.jar
  base/uk.ac.stfc.isis.ibex.databases/lib/mysql-connector-java-8.0.25.jar
  base/uk.ac.stfc.isis.ibex.devicescreens/pom.xml
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
  base/uk.ac.stfc.isis.ibex.epics/.classpath
  base/uk.ac.stfc.isis.ibex.epics/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.epics/build.properties
  base/uk.ac.stfc.isis.ibex.epics/lib/joda-time-2.10.10.jar
  base/uk.ac.stfc.isis.ibex.epics/lib/joda-time-2.10.6.jar
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
  base/uk.ac.stfc.isis.ibex.logger/.classpath
  base/uk.ac.stfc.isis.ibex.logger/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.logger/build.properties
  base/uk.ac.stfc.isis.ibex.logger/lib/log4j-api-2.13.3.jar
  base/uk.ac.stfc.isis.ibex.logger/lib/log4j-api-2.14.1.jar
  base/uk.ac.stfc.isis.ibex.logger/lib/log4j-core-2.13.3.jar
  base/uk.ac.stfc.isis.ibex.logger/lib/log4j-core-2.14.1.jar
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
  base/uk.ac.stfc.isis.scriptgenerator.client.product/scriptgenerator.product
  base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml
  base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml
Labels: size/L

#1327 Interrupt script console only if it exists
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/InterruptScript.java
Labels: size/S
