Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-03, with the labels that each got.

#1262 Update platform
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1263 Ticket5938
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py
  base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini
Labels: size/M

#1259 Disable controls on DISP
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/action_bar.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/correction.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/full_opi.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_align.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_highlighted.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_with_cv.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_constants.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/value.opi
Labels: size/XXL

#1265 Hide controls when sp mirrors rbv and show message
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_highlighted.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_with_cv.opi
Labels: size/L

#1274 Point at ICP P2 area
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
Labels: size/XS

#1271 Update TPG to use scientific notation if very small
  base/uk.ac.stfc.isis.ibex.opis/resources/TPGx6x_common.opi
Labels: size/L
