Repository ISISComputingGroup/ibex_gui, pull requests merged in 2021-12, with the labels that each got.

#1382 Ticket6743 Added buttons to stop relevant motors to the OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/L

#1368 add mntcycles sp to opi
  base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi
Labels: size/M

#1384 add Dlog4j2.formatMsgNoLookups=true to ibex.product
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
Labels: size/XS

#1379 Created OPI for Wish Jaws but a couple of PVs are missing
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1387 Update references to new log4j
  base/uk.ac.stfc.isis.ibex.logger/.classpath
  base/uk.ac.stfc.isis.ibex.logger/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.logger/build.properties
Labels: size/S
