Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-01, with the labels that each got.

#1383 Update max_array_bytes
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
Labels: size/XS

#1389 removed uneccesary LED and spinners
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi
Labels: size/L

#1390 making build.bat more verbose
  build/build.bat
Labels: size/XS

#1386 adding beckhoff engineering view opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/spinner_choose_axis.py
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi
Labels: size/XL

#1392 Added additional tab for 6th IOC
  base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L
