Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-11, with the labels that each got.

#1498 Fix serialization again
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/json/LowercaseEnumTypeAdapterFactoryTest.java
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/json/LowercaseEnumTypeAdapterFactory.java
Labels: size/S

#1494 Ticket7268
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/IocState.java
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.ui.configserver/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/EditableIocsTable.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocPanel.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocPanelHandler.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/table/IOCRunModeProvider.java
Labels: size/L

#1499 Ticket7070
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_align.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list_redefine.opi
Labels: size/XXL

#1506 Add standalone general i/o screen
  base/uk.ac.stfc.isis.ibex.opis/resources/galil/general_io_standalone.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1501 Ticket6079 add ioc aeroflex
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1502 Ticket7073
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_align.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list_advanced.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_highlighted.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_with_cv.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_advanced.opi
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryAdvancedTargetView.java
Labels: size/XL

#1504 Ticket7225
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/EditableConfigurationTest.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/DisplayUtils.java
  base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/InstrumentSwitchers.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigDetailsDialog.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/groups/GroupsEditorPanel.java
Labels: size/L

#1508 Add test case
  base/uk.ac.stfc.isis.ibex.opis/resources/rules_tests.opi
Labels: size/L

#1507 add jog LEDs, disable jog buttons and home buttons respectively if re…
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
Labels: size/XXL

#1505 add sandals jaws manager opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/sandals_manager.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL
