Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-05, with the labels that each got.

#1347 Ticket 5238: Show/hide perspectives
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/CopyPerspectiveSnippetProcessor.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/PerspectiveInfo.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/PerspectivePreferenceSupplier.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/PerspectivesProvider.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/PerspectivesVisibleModel.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/commands/SelectVisiblePerspectives.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/Button.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/ButtonViewModel.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/PerspectiveButtonViewModel.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/PerspectivesTable.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/ResetLayoutButtonModel.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveHidingDialog.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveSwitcherView.java
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/json/JsonSerialisingConverter.java
  base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModeModel.java
  base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosModel.java
  base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
  base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/CheckboxLabelProviderTest.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksTable.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/EditableIocsTable.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/MacroTable.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvsets/IocPVSetsTable.java
  base/uk.ac.stfc.isis.ibex.ui.logplotter/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/ButtonCellLabelProvider.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/CheckboxLabelProvider.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/ControlCellLabelProvider.java
  base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/SortableObservableMapCellLabelProvider.java
Labels: size/XXL

#1276 Ticket6240 3he fridge cryo logic
  base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi
Labels: size/XXL

#1412 uncomment nicos code
  base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosModel.java
Labels: size/S

#1277 Add initial GUI
  base/uk.ac.stfc.isis.ibex.opis/resources/biologic/SP300.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/biologic/SP300_single.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1411 Ticket7134 OPI and its mention removed
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/full_opi.opi
Labels: size/XXL

#1410 add live updating web view to tosca sample changer OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/tosca_sample_changer/tosca_sample_positioner.opi
Labels: size/XL

#1413 Add webcam opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam.opi
Labels: size/XXL

#1415 Ticket6243 hardware testing
  base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi
Labels: size/L

#1400 Ticket7060 GUI: Fix text in groups panel disappearing when resizing
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java
Labels: size/XS

#1417 Ticket7137 bug fixed
  base/uk.ac.stfc.isis.ibex.ui.banner/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocControlHandler.java
Labels: size/S

#1421 Use webcam opi for tosca smpchng
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/tosca_sample_changer/tosca_sample_positioner.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam_image.opi
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/L

#1422 Fix opi_info.xml corrupted by Technix PSU merge.
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS
