Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-10, with the labels that each got.

#1485 Ticket #7386
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectraplots/PersistedLocalChannel.java
Labels: size/M

#1484 HTS niggles
  base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
Labels: size/XXL

#1487 Ticket6382
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorProperties.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/AbstractGenerator.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorContext.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorPython.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ScriptGeneratorAction.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/XL

#1490 Ticket 7401
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/BannerButtonTest.java
  base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/desc/tests/DeviceScreensDescriptionToXmlConverterTest.java
  base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/tests/DeviceScreenVariablesTest.java
  base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/WritableFactory.java
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/switching/SwitchableObservableTest.java
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/switching/WritableFactoryTest.java
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/switching/WritablePrefixChangingSwitcherTest.java
  base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java
  base/uk.ac.stfc.isis.ibex.nicos.tests/src/uk/ac/stfc/isis/ibex/nicos/ZMQSessionTest.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/utils/ScriptGeneratorMockBuilder.java
  base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/internal/VariablesTest.java
  base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/CheckboxLabelProviderTest.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/groups/GroupsEditorPanel.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/IocPVDetailsPanel.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsPanel.java
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails.tests/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/tests/ExperimentDetailsViewModelTest.java
  base/uk.ac.stfc.isis.ibex.ui.tests/src/uk/ac/stfc/isis/ibex/ui/tests/ASyncEventLimiterTest.java
  base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml
Labels: size/L

#1492 Ticket7406
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibViewModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCursorPosition.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigure.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigureViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketModel.java
Labels: size/L

#1491 adding IOCNAME into mtr details page
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/M

#1493 Remove finalizers
  base/uk.ac.stfc.isis.ibex.banner/src/uk/ac/stfc/isis/ibex/banner/ObservableCustomControl.java
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreens.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreensModel.java
  base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/CustomControlModel.java
  base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/views/BannerView.java
Labels: size/M

#1496 Fix deserialization of attributes marked with @SerializedName
  base/uk.ac.stfc.isis.ibex.configserver/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.epics.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/json/LowercaseEnumTypeAdapterFactoryTest.java
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/json/LowercaseEnumTypeAdapterFactory.java
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/M
