Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-06, with the labels that each got.

#1418 only show coarse/fine move box if in manager mode
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/tosca_sample_changer/tosca_sample_positioner.opi
Labels: size/M

#1420 Ticket7168 3he fixes
  base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi
Labels: size/L

#1416 Ticket 6774 pearlpc cell and pump pressure
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/XXL

#1425 Update PULL_REQUEST_TEMPLATE
  PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#1426 Add pressure and pressure difference to opi. Fix graph updates.
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/L

#1428 Ticket 7193
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/XXL

#1431 Add chan 8-10 tabs to Eurotherm OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
Labels: size/XXL

#1419 Ticket7138 Introducing a potential fix to the problem entirely
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupText.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
Labels: size/M

#1427 Gp2 gui
  base/uk.ac.stfc.isis.ibex.opis/resources/GP2.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/GP2Setup.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/GP2item.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/areaDetector/2DView.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1430 Add BUSY pv to OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/L

#1435 enable PREC from PV for FMR PVs
  base/uk.ac.stfc.isis.ibex.opis/resources/fmr.opi
Labels: size/M

#1436 Resize graphs and fix local variables
  base/uk.ac.stfc.isis.ibex.opis/resources/GP2.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/areaDetector/2DView.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/live_view/live_view.opi
Labels: size/L

#1429 Add warning on OPI if eurotherm started with no channels configured
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
Labels: size/M

#1432 Use /MIR flag on client install
  build/install_client.bat
  build/install_script_generator.bat
Labels: size/XS
