Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-03, with the labels that each got.

#1398 Ticket7039 GUI groups panel improvements
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupRow.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java
Labels: size/L

#1399 adding hexed error id, sensible default for axis num spinner, axis nu…
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi
Labels: size/L

#1397 Resize height and fix tab0 xpos
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
Labels: size/M

#1402 switching from text input to label for wish jaw readback values
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi
Labels: size/XXL

#1401 Ticket 6574 GUI add a refresh button
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/icons/resetpv.png
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/RefreshPvConnectionButton.java
  base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveSwitcherView.java
  base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/InstrumentSwitchers.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupRow.java
Labels: size/M

#1403 Remove compact matplotlib view & separate plot viewpart in refl persp…
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.opis/resources/matplotlib_compact.opi
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/ConnectionHandler.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/FixedMatplotlibOpiTargetView.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/MatplotlibOpiTargetView.java
  base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Consoles.java
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/GeniePythonConsoleFactory.java
Labels: size/L

#1369 Ticket5154 Added OPI for DG645 in a modular fashion, to be reused if needed
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ErrorReadback.py
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.py
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/RBGeneric.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/RBTrigger.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/SPGeneric.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/SPTrigger.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/delay_generators.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/delay_generators_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL
