Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-08, with the labels that each got.

#1447 Ticket6425 add file checks
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/inout_motion_setpoints.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position_part.opi
Labels: size/XL

#1455 make script gen persp icon smaller and less colourful
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.ui.help/resources/iconlicences.txt
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/icons/scriptgenerator_24.png
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/icons/scriptgenerator_32.png
Labels: size/XS

#1456 fixing 'edit host configuration' menu item
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
Labels: size/M

#1437 Add transtechnik OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/transtechnik.opi
Labels: size/XXL

#1459 Checkstyle
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/IocDescriber.java
  base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
  base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/internal/UnknownParameter.java
  base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/internal/UserDetailsSerialiser.java
  base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/channels/FloatArrayChannel.java
  base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/internal/UserName.java
  base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/FilterPredicate.java
  base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/ReadWritableValue.java
  base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/ReadableValue.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/BeamStatusGraphDataProvider.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ButtonCellLabelProvider.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/DoubleListEditor.java
  base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/IconConventionsCheckTest.java
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/ConfigureDeviceScreensListPanel.java
  base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
  base/uk.ac.stfc.isis.ibex.ui.nicos.tests/src/uk/ac/stfc/isis/ibex/ui/nicos/tests/QueueScriptViewModelTest.java
  base/uk.ac.stfc.isis.ibex.ui.synoptic.editor.tests/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/validators/tests/DuplicatePvValidatorTest.java
  base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/WritableComponentView.java
  base/uk.ac.stfc.isis.ibex.ui.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/DoubleEditingSupportBlankIfNull.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/IntegerEditingSupportBlankIfNull.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/VerticalGradientComposite.java
  base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/NumbersOnlyValidator.java
Labels: size/XL

#1453 Ticket7253 tjmper phase 1
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/tjmper.opi
Labels: size/XXL

#1452 Ticket 3736
  base/uk.ac.stfc.isis.ibex.ui.blocks/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java
  base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/views/BlocksView.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockRunControlPanel.java
  base/uk.ac.stfc.isis.ibex.ui.runcontrol/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/commands/RunControlHandler.java
  base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/EditRunControlDialog.java
Labels: size/M

#1458 Reflectometry performance
  base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
  base/uk.ac.stfc.isis.ibex.opis/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.opis/build.properties
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/action_bar.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/populate_list.py
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setTooltipFromDescription.py
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_front_panel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_redefine.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/rules_tests.opi
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/Opi.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/OpiView.java
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
  base/uk.ac.stfc.isis.ibex.ui.synoptic.editor.tests/META-INF/MANIFEST.MF
Labels: size/XXL

#1460 Add % of Volt Limit to Pressure and Temp Cards on Mercury Cryostat GUI
  base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_pressure.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_temp.opi
Labels: size/L

#1461 Add TTIPLP Trip Information to GUI
  base/uk.ac.stfc.isis.ibex.opis/resources/ttiplp.opi
Labels: size/XL

#1457 Ticket7261
  base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore336/Lakeshore336.opi
Labels: size/L

#1464 Ticket7224
  base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml
Labels: size/XS

#1465 Ticket7133 log plotter disabled notification
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java
Labels: size/S
