Repository ISISComputingGroup/ibex_gui, pull requests merged in 2022-09, with the labels that each got.

#1467 Use local .m2 location
  .gitignore
  build/build.bat
  build/build_script_generator.bat
Labels: size/XS

#1462 Better matplotlib backend
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/ModelObject.java
  base/uk.ac.stfc.isis.ibex.opis/resources/matplotlib.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/.classpath
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/.project
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/build.properties
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/pom.xml
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibViewModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/ConnectionHandler.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/GraphingConnector.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/MatplotlibOpiTargetView.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/Activator.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibAllFiguresView.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibAllPrimaryFiguresView.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibAllSecondaryFiguresView.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigure.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigureViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketModel.java
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java
  base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/dialogs/WaitForDialog.java
Labels: size/XXL

#1469 Appease checkstyle
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/Activator.java
Labels: size/XS

#1463 Change text input to spinner with 500V steps
  base/uk.ac.stfc.isis.ibex.opis/resources/technix.opi
Labels: size/L

#1471 Depend on tyrus via maven rather than via custom P2 site
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
  base/uk.ac.stfc.isis.ibex.ui.graphing/META-INF/MANIFEST.MF
Labels: size/S

#1474 Remove hexed from error ID label in twincat OPI as it is actually num…
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
Labels: size/XS

#1468 5470 add hide title to exp view add python genie
  base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/ObservableExperimentDetailsModel.java
  base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/internal/ExperimentDetailsVariables.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/run/RunSummary.java
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/ExperimentDetailsPanel.java
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/ExperimentDetailsViewModel.java
Labels: size/M

#1475 #5470 adds mocked observable and writable for new checkbox in experim…
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails.tests/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/tests/ExperimentDetailsViewModelTest.java
Labels: size/XS

#1473 4673 Eurotherm Single Temperature Sensor
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single_temp.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1476 Ticket7328
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/hgaps.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/important_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/sample_stack.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/vgaps.opi
Labels: size/XXL

#1477 Linux rpm
  base/uk.ac.stfc.isis.ibex.instrument/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/list/InstrumentListObservable.java
  base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/run_tests.sh
  base/uk.ac.stfc.isis.ibex.ui.dashboard/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/TitlePanel.java
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/ExperimentDetailsPanel.java
  base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
  base/uk.ac.stfc.isis.ibex.ui.mainmenu/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/instrument/InstrumentSelectionPanel.java
  base/uk.ac.stfc.isis.ibex.ui/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/Utils.java
  build/build.sh
  build/build_rpm.sh
  build/ibex-client.spec
  build/run_python_support_tests.sh
Labels: size/L

#1470 Ticket7296 instron arby
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/stress_rig/stress_rig.opi
Labels: size/S

#1481 Ticket7342
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/XS

#1482 Ticket7381
  base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchWindowAdvisor.java
Labels: size/M

#1480 Ticket7376
  base/uk.ac.stfc.isis.ibex.opis/resources/keylkg.opi
Labels: size/XL
