Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-11, with the labels that each got.

#1624 Add setEnabled script to pressure sp and control buttons
  base/uk.ac.stfc.isis.ibex.opis/resources/Common Scripts/setEnabled.py
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/M

#1626 make maven parallelised
  build/build.bat
Labels: size/XS

#1635 Ticket8013 unhide unit
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/VTypeFormatDefaultFormatterAndQuantityTest.java
Labels: size/S

#1622 DAE remains grey if the main is not Localhost
  base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/PanelViewModel.java
Labels: size/S

#1636 Ticket8097 add missing taps
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_table_25_to_32.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/temperature_table.opi
Labels: size/XL

#1638 Ticket8069_apply_enum_dropdown_fix
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/EnumEditingSupport.java
Labels: size/XS

#1640 Ticket8108 script gen refactor
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/IBEXButtonFactory.java
Labels: size/XXL

#1619 add manager mode visible statement to pearl alignment motor controls
  base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi
Labels: size/XL

#1643 Place script definition selector in the same container as the label
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
Labels: size/XS

#1642 Ticket6899 script gen invalid action
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsValidityChangeListener.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/XXL
