Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-07, with the labels that each got.

#1565 Ticket7895
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/displaying/DisplayBlockTest.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
Labels: size/M

#1546 fix minor riken issues
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/RIKEN_magnet_PSUs.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_kicker.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_technix.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_transtechnik.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/psu_magnet_status_XFD.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/RIKEN_vacuum_synoptic.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/vacuum valve.opi
Labels: size/XXL

#1564 Ticket6045
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/horizontal_jaws.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/pearl_manager.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/single_horizontal_jaw_manager.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1574 Removed set buttons for RF and CarFreq, pointed fields at appropriate PVs
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1568 Removed set modulation type buttons, dropdown, etc.
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1571 Ticket7881
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1570 Ticket7879
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1575 added a reset timestamp opu and indicator
  base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2700/keithley_scanner_values.opi
Labels: size/XXL

#1569 Ticket 7877 opi
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1566 Ticket6041 add ioc measm905
  base/uk.ac.stfc.isis.ibex.opis/resources/MEASM905/measm905.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1558 Ticket6044
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
Labels: size/XXL

#1576 added missing connection to LED PV
  base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2700/keithley_scanner_values.opi
Labels: size/XS
