Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-10, with the labels that each got.

#1608 OPI updates to Aeroflex - Remote and Local Button
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
Labels: size/L

#1616 Added the changes in Thomas' ticket comment
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/templates/generator_template.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ScriptGeneratorAction.java
Labels: size/S

#1591 Changed doGitActions to remove user ability to update
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/L

#1612 Ticket7649
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
Labels: size/L

#1618 Add rule and script to disable tab if not in manager mode and switch …
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/S

#1615 add clause for not disabling home button for a beckhoff
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
Labels: size/S

#1614 Ticket7975 add ioc rknmntr
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_table_13_to_14.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_table_1_to_12.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_tap_row.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/temperature_table.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1621 make beckhoff engineering view show error code lookup and show 8 axes…
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/spinner_choose_axis.py
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi
Labels: size/XXL

#1620 show diagnostic stuff in simple motor view if using beckhoff/galil an…
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
Labels: size/XL

#1623 Show magnet current in tabs
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_current.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/temperature_table.opi
Labels: size/XL

#1631 remove units sp option, add vent status and SP
  base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
Labels: size/XL

#1627 remove S4 and add Monitor3 on front panel
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/hgaps.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/important_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/vgaps.opi
Labels: size/L

#1632 remove superfluous mm label from pearl jaws manager opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/pearl_manager.opi
Labels: size/XL

#1629 show full filepath for motion setpoints
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position_part.opi
Labels: size/S

#1633 Ticket8013 unhide unit
  base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/VTypeFormatToConversionsTest.java
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/VTypeDefaultFormatter.java
Labels: size/M
