Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-01, with the labels that each got.

#1517 fix dae status indicator, add test for this
  base/uk.ac.stfc.isis.ibex.ui.banner.tests/src/uk/ac/stfc/isis/ibex/ui/banner/tests/ServerStatusViewModelTest.java
  base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatusViewModel.java
Labels: size/S

#1518 fix checkstyle - remove unused import of java.util.List
  base/uk.ac.stfc.isis.ibex.ui.banner.tests/src/uk/ac/stfc/isis/ibex/ui/banner/tests/ServerStatusViewModelTest.java
Labels: size/XS

#1513 Ticket7058
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/superlogics.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/value.opi
Labels: size/XXL

#1521 Run the tests in the GUI
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.model.tests/pom.xml
Labels: size/M

#1486 Add Custom Vacuum Synoptic OPI for RIKENFE
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/PumpsetIndicator.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/PumpsetSummary.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/RIKEN_Vacuum_Pumpset.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/RIKEN_vacuum_synoptic.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Vacuum Status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Valve Disconect.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Valve Fault.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Valve Open.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Valve Sweeping.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/Valve close.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/vacuum valve.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/semi circle led off flipped.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/semi circle led off.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/semi circle led on flipped.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/semi circle led on.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/solenoid kickers off.png
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/solenoid kickers on.png
  base/uk.ac.stfc.isis.ibex.opis/resources/icons_for_opis/Check Mark.png
  base/uk.ac.stfc.isis.ibex.opis/resources/icons_for_opis/Cross.png
  base/uk.ac.stfc.isis.ibex.opis/resources/icons_for_opis/ReadMe
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1524 Link matplotlib toolbar icons to maven build
  base/uk.ac.stfc.isis.ibex.ui.graphing/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.graphing/build.properties
Labels: size/XS

#1523 Add OPI for keithley 2000
  base/uk.ac.stfc.isis.ibex.opis/resources/keithley_2000.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL
