Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-05, with the labels that each got.

#1541 Fix code, add tests, add dependency
  base/uk.ac.stfc.isis.ibex.configserver.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/ConfigInfoTest.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/M

#1545 Added icons for LOQ
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/single_aperture.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/single_aperture_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/vertical_aperture_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/vertical_aperture.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/M

#1547 Added method to check name conventions and content of Test files
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/doubles/LoggingPropertyChangeListener.java
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/doubles/LoggingWritableValue.java
  base/uk.ac.stfc.isis.ibex.opis.tests/src/uk/ac/stfc/isis/ibex/opis/tests/desc/XmlDuplicateCheckTest.java
  base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/navigation/ComponentlessInstrument.java
  base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/.project
  base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/IconConventionsCheckTest.java
  base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/IconConventionsTest.java
  build/check_build.py
Labels: size/L

#1548 updated OPI to display high/low
  base/uk.ac.stfc.isis.ibex.opis/resources/nimatro.opi
Labels: size/XXL
