Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-06, with the labels that each got.

#1553 Initial Hexagon GUI
  base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_energyspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_hvchannel.opi
Labels: size/XXL

#1552 added a global variable to switch on if default flag changes from fal…
  base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/selector/TargetSelectorViewModel.java
Labels: size/XS

#1549 Ticket6922 script generator read only when excuting step
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorEditingSupport.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/StringEditingSupport.java
Labels: size/M

#1555 changed logic to complie with changestyle
  base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/selector/TargetSelectorViewModel.java
Labels: size/XS

#1551 Added rightclick menu to script generator
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/L

#1554 Ticket4390 read homing routines as pv
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/galil/single_axis_params.opi
Labels: size/L

#1556 Added PVs to beam information tab
  base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS2Observables.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/TargetStationTwoPanel.java
Labels: size/M

#1557 Ticket 7837
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/XS
