Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-04, with the labels that each got.

#1530 Add heater on time OK indicator to IPS OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi
Labels: size/XXL

#1542 Fix double creation.
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/HelpButton.java
Labels: size/XS

#1538 Dependency update
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.databases/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/tests/xmldata/DeviceScreensXmlProvider.java
  base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/xml/tests/XmlUtilTest.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/DeviceDescription.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/DeviceScreensDescription.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/PropertiesDescription.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/PropertyDescription.java
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/package-info.java
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
  base/uk.ac.stfc.isis.ibex.epics/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/XMLUtil.java
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
  base/uk.ac.stfc.isis.ibex.instrument.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/pv/PVType.java
  base/uk.ac.stfc.isis.ibex.jaxb/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.jaxb/src/uk/ac/stfc/isis/ibex/jaxb/JAXB.java
  base/uk.ac.stfc.isis.ibex.nicos/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/ZMQWrapper.java
  base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/ReceiveBannerMessage.java
  base/uk.ac.stfc.isis.ibex.opis.tests/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.opis.tests/src/uk/ac/stfc/isis/ibex/opis/tests/desc/DescriptionsProviderTest.java
  base/uk.ac.stfc.isis.ibex.opis.tests/src/uk/ac/stfc/isis/ibex/opis/tests/desc/XmlDuplicateCheck.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/Descriptions.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/MacroInfo.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/OpiDescription.java
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/package-info.java
  base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/xml/example_synoptic.xml
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/ComponentDescription.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/IO.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/PV.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/Property.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/RecordType.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/SynopticDescription.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/TargetDescription.java
  base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/package-info.java
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
  base/uk.ac.stfc.isis.ibex.ui.banner/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.blocks/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.scripting/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java
  build/build.bat
  build/copy_in_maven.bat
Labels: size/XL

#1540 Add batching deferring property change listener wrappers
  base/uk.ac.stfc.isis.ibex.model.tests/src/uk/ac/stfc/isis/ibex/model/tests/DeferredPropertyChangeListenerTest.java
  base/uk.ac.stfc.isis.ibex.model/.settings/org.eclipse.jdt.core.prefs
  base/uk.ac.stfc.isis.ibex.model/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/DeferredPropertyChangeListener.java
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsPanel.java
Labels: size/L

#1539 Ticket7663 add ioc kse4980
  base/uk.ac.stfc.isis.ibex.opis/resources/kse4980.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1537 Added motion setpoints error message to SANS sample changer OPI.
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
Labels: size/L
