Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-02, with the labels that each got.

#1522 Ticket7461
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibViewModelTests.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCanvasData.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCursorType.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibDragSelectionType.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigure.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigureViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibToolbar.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
  base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketModel.java
Labels: size/L

#1525 update target platform to pydev branch for disabling autocomplete
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/S

#1515 Added Keithley 2290 power supply OPI.
  base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2290/Keithley2290.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1516 Ticket6931 eurotherm output rate control
  base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi
Labels: size/L

#1510 Ticket5876: Add Kicker/Separator HV settings OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/Kickers/individual_kicker_row.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/Kickers/individual_separator_row.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/Kickers/kickers_and_seperators.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/RIKEN_magnet_PSUs.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/Opi.java
Labels: size/XXL

#1526 Ticket7542
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/L

#1519 Ticket7515
  base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/internal/ImportConverterTest.java
  base/uk.ac.stfc.isis.ibex.configserver/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/ImportConverter.java
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/components/tests/ComponentNameSearchTest.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/ImportVariables.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/ImportComponentHandler.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ImportComponentDialog.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/components/ComponentNameSearch.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/components/ComponentTable.java
  base/uk.ac.stfc.isis.ibex.ui.mainmenu/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/LinkWrapper.java
Labels: size/XXL

#1527 Ticket7561
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/setup_graph.py
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/superlogics.opi
Labels: size/XL

#1528 Removed space in RIKEN vacuum target
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1532 Remove rule.
  base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper_Master.opi
Labels: size/XS
