Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-08, with the labels that each got.

#1578 Ticket7909 recopy pydev cmdhist
  build/install_gui_with_builtin_python.bat
Labels: size/S

#1577 Ticket7891 dg645 input
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelDelay.opi
Labels: size/M

#1572 Ticket7720 moxa mappings
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Configurations.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/Converters.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/json/JsonConverters.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/json/MoxaMappingsConverter.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/pv/BlockServerAddresses.java
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.e4.client/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.e4.client/src/.gitkeep
  base/uk.ac.stfc.isis.ibex.e4.client/src/ReadMe.txt
  base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
  base/uk.ac.stfc.isis.ibex.ui.help/resources/iconlicences.txt
  base/uk.ac.stfc.isis.ibex.ui.moxas/.classpath
  base/uk.ac.stfc.isis.ibex.ui.moxas/.project
  base/uk.ac.stfc.isis.ibex.ui.moxas/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.moxas/build.properties
  base/uk.ac.stfc.isis.ibex.ui.moxas/icons/moxa_24x24.png
  base/uk.ac.stfc.isis.ibex.ui.moxas/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.moxas/pom.xml
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaList.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaModelObject.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaTableContentProvider.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasView.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java
Labels: size/XL

#1582 KEPCO: display current range mode
  base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
Labels: size/XL

#1584 Ticket7888 save load sttgs
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelDelay.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Burst.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Delay.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Manage.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Outputs.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645StatusRegister.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Trigger.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
Labels: size/XXL

#1559 Create OPI for separator tuning
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/psu_control.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/separator_tuning.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/technix.opi
Labels: size/XXL

#1567 Ticket6042
  base/uk.ac.stfc.isis.ibex.opis/resources/dhp30330.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1543 Ticket6777
  base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1585 Ticket7875 add iologik1242 to our ioc
  base/uk.ac.stfc.isis.ibex.opis/resources/moxa1242.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1587 add inter beckhoff diagnostics OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1563 Update TPG300 OPI to support TPG500
  base/uk.ac.stfc.isis.ibex.opis/resources/TPG300.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1588 Add event spectra files
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_eventspec.opi
Labels: size/XXL
