Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-12, with the labels that each got.

#1644 Ticket5496_script_gen_load_params
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/IBEXButtonFactory.java
Labels: size/L

#1648 add stop kinematics button which sends 0 to RUN_KINEMATICS
  base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
Labels: size/M

#1647 Add missing dummy widgets to opis
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_eventspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/psu_control.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/separator_tuning.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/dhp30330.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag_advanced.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/moxa1242.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi
Labels: size/XL

#1646 Fixed Tab out issue for enum scripts
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
Labels: size/M

#1651 swapping height and height2 on offspec sample stack panel
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/sample_stack.opi
Labels: size/XS

#1641 Ticket6136 add opi lm500
  base/uk.ac.stfc.isis.ibex.opis/resources/LM500.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/LM500_status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1657 fix checkstyle - suppression not working
  base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettings.java
  base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettingsProperties.java
Labels: size/M

#1645 Dispatch property change event on UI thread
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupSpinner.java
Labels: size/L

#1658 set JAVA_TOOL_OPTIONS env variable to disable CEN header checks
  build/build.bat
  build/build_script_generator.bat
Labels: size/XS

#1660 disable parallel build for the moment
  build/build.bat
Labels: size/XS
