Repository ISISComputingGroup/ibex_gui, pull requests merged in 2023-09, with the labels that each got.

#1586 Changed fault LED red colour
  base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi
Labels: size/XXL

#1592 Ticket7820 add ioc pre4500
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi
Labels: size/XL

#1590 New OPI for PEARL Sample Alignment created from mymotor copy
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi
Labels: size/XXL

#1596 Synchronise graphs
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.py
Labels: size/S

#1598 Fixed missing closing tags in opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1597 fix beam status block local box
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewBlockHandler.java
Labels: size/M

#1599 Update pre4500.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi
Labels: size/XS

#1604 DG645 automatically applied OPI formatting changes
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
Labels: size/XXL

#1603 Added labels to DG645 right displays
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1607 fix time axis for pre4500 - see NDXMERLIN vs local client
  base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi
Labels: size/M

#1606 Ticket7896 iocs in use
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaModelObject.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java
Labels: size/L

#1605 DG645 Delay Generator - Add units to Readback Delay (real changes)
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
Labels: size/L

#1613 Ticket7632 perspective help icons
  base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
  base/uk.ac.stfc.isis.ibex.opis/resources/icons_for_opis/helpIcon.png
  base/uk.ac.stfc.isis.ibex.opis/resources/icons_for_opis/help_icon_24.png
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_activation_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_advanced.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_collimation_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_constants.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_corrections.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_error_log.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_front_panel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_other_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_slit_params.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/template.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/NicosStatusContainer.java
  base/uk.ac.stfc.isis.ibex.ui.scripting/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.scripting/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/ConsoleHelpButton.java
Labels: size/XL

#1601 Add heartbeat for traces' x PV
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/separator_tuning.opi
Labels: size/M

#1611 typo
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasView.java
Labels: size/XS
