Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-08, with the labels that each got.

#1731 Stanford sr400 device screen icon
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/photon_counter.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/photon_counter_tb.png
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XS

#1732 Ticket#8465 Fixed visual changes in Environment Monitor OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/envmon.opi
Labels: size/L

#1733 Fixes checkstyle and system tests
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/icons/components/thumbs/photon_counter_tb.png
Labels: size/XS

#1734 update pydev
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/XS

#1737 add opi for chipir xyz table
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL
