Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-07, with the labels that each got.

#1721 remove some floating text fields which are already displayed
  base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
Labels: size/L

#1700 change sm in beam (no longer used) to FOM in beam
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/SURF/important_params.opi
Labels: size/XS

#1719 Ticket6210 chipir hameg
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL

#1725 Fixes 670841c2fa5705f21438d340a6624a427b85a45e
  base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi
Labels: size/XS

#1724 Added identifying motor controller to collimator OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi
Labels: size/XXL

#1722 Ticket 8329
  build/jenkins_build.bat
  build/jenkins_build_script_generator.bat
Labels: size/XS

#1714 Ticket8265 add ioc dds stress rig
  base/uk.ac.stfc.isis.ibex.opis/resources/dds_tensile_stress_rig.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1727 Replace uses of =1 with loc:// pvs
  Jenkinsfile
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hrpd_in_situ_dsc.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/horizontal_jaws.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_base.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/superlogics.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi
Labels: size/L

#1728 Demote font definitions check to non-strict
  base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
Labels: size/S

#1729 small typo in beam status pvs
  base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS2Observables.java
Labels: size/XS

#1730 bug - tekdmm40X0 hardcoded to only show first IOC
  base/uk.ac.stfc.isis.ibex.opis/resources/tekdmm40X0.opi
Labels: size/XS
