Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-06, with the labels that each got.

#1709 opi for chipir collimator
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_collimator/chipircollimator.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_collimator/collimator.png
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1710 Ticket6029 add ioc sr850
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/sr850.opi
Labels: size/XL

#1713 Set the search bar of the Add IOC panel to be focused on load
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/AddPanel.java
Labels: size/XS

#1712 Change SR850 device screen type to OSCILLOSCOPE
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1703 Use original opi file in tabbed view as the default control ui
  base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000_single.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000_single_old.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1711 Ticket6214 add ioc stanford sr400 photon counter
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/stanford_sr400_photon_counter.opi
Labels: size/XXL

#1715 Add missing xml tags to opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1716 Disable Zip64 validation for jython
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
Labels: size/XS

#1718 fix container size in zfmagfld
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller/field_strength.opi
Labels: size/XS
