Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-01, with the labels that each got.

#1649 Ticket8118 script gen mvvm refactor
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsValidityChangeListener.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModelDelegate.java
Labels: size/XL

#1661 disable adding block when there are no configs to add it to
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java
Labels: size/S

#1663 Include original enable condition for handler
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java
Labels: size/XS

#1655 ticket8123_parse_console_output
  Jenkinsfile
  parse_rules
Labels: size/S

#1653 Ticket5879_argus_magnet_status_opi
  base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
  base/uk.ac.stfc.isis.ibex.opis/resources/ARGUS/magnet_status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
Labels: size/XXL

#1665 Change parse rules and disable unstableOnWarning
  Jenkinsfile
  parse_rules
Labels: size/XS

#1662 Ticket7995 disable adding bs block if server down
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
  base/uk.ac.stfc.isis.ibex.instrument.status/src/uk/ac/stfc/isis/ibex/instrument/status/ServerStatusVariables.java
  base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/views/BannerView.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocControlHandler.java
Labels: size/XL

#1666 Declare ServerStatusVariables class final and add javadoc to satisfy …
  base/uk.ac.stfc.isis.ibex.instrument.status/src/uk/ac/stfc/isis/ibex/instrument/status/ServerStatusVariables.java
Labels: size/XS

#1667 invoke layout on global params container to show them again on script…
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
Labels: size/XS

#1671 re enable auto complete in pydev
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/S

#1672 Added utility to get Debug port
  base/uk.ac.stfc.isis.ibex.utilities/.classpath
  base/uk.ac.stfc.isis.ibex.utilities/.project
  base/uk.ac.stfc.isis.ibex.utilities/src/uk/ac/stfc/isis/ibex/utilities/GetVMInfo.java
Labels: size/L

#1656 Ticket8109: Changes to display Connection status in Moxa View
  base/uk.ac.stfc.isis.ibex.ui.moxas/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaModelObject.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java
Labels: size/L

#1673 Update to pom.xml
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
Labels: size/XS

#1674 Ticket 8185 ibex gui retain moxa display state
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Configurations.java
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/LoggingObserver.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java
Labels: size/M

#1675 change beckhoff eng. view to allow TC_XX
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
Labels: size/M
