Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-04, with the labels that each got.

#1687 Add message about server still running on client close
  base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchAdvisor.java
Labels: size/XS

#1686 Ticket8210 add ioc lndyisw
  base/uk.ac.stfc.isis.ibex.opis/resources/lndyisw.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1693 add option to add PV to clipboard from device screen/ToM/beam status view
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/CopyPVToClipboardHandler.java
Labels: size/L

#1691 Fix accidental reversion of several gui changes
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Configurations.java
  base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
  base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
  base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/LoggingObserver.java
  base/uk.ac.stfc.isis.ibex.instrument.status/src/uk/ac/stfc/isis/ibex/instrument/status/ServerStatusVariables.java
  base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/he3nmr/he3nmr.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/he3nmr/nmrscreen.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/populate_list.py
  base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/string_value.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSettingsSingleton.java
  base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/dynamicscripting/PlayingState.java
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
  base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/views/BannerView.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockSetPanel.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockSetViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java
  base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocControlHandler.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/META-INF/MANIFEST.MF
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaModelObject.java
  base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
  base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
  base/uk.ac.stfc.isis.ibex.utilities/.classpath
  base/uk.ac.stfc.isis.ibex.utilities/src/uk/ac/stfc/isis/ibex/utilities/GetVMInfo.java
  build/copy_in_maven.bat
  parse_rules
Labels: size/XXL

#1695 Add warning label
  base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
Labels: size/XXL

#1690 Add input fields for compliance volt and curr, and set limits for them
  base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/SourceMode.opi
Labels: size/L

#1697 Fix typo in summary script
  base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplayChannels.py
Labels: size/XS

#1696 fix build - nebula.visualization duplication issue in target platform
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
Labels: size/XS

#1682 Add stanford ps300 series OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/PS300.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL
