Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-09, with the labels that each got.

#1735 Ticket6217 chipir opi for filter set
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_filter_set.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XXL

#1738 Add CAENV895 CRATE macro
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS

#1739 Delete base/uk.ac.stfc.isis.ibex.utilities directory
  base/uk.ac.stfc.isis.ibex.utilities/.classpath
  base/uk.ac.stfc.isis.ibex.utilities/.project
  base/uk.ac.stfc.isis.ibex.utilities/src/uk/ac/stfc/isis/ibex/utilities/GetVMInfo.java
Labels: size/L

#1740 Ticket6232 ability to edit tpar file within ibex
  base/uk.ac.stfc.isis.ibex.opis/resources/TPAR_Editor/tpar_editor.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1741 lindy i power switch - default value for OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XS
