Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-11, with the labels that each got.

#1684 Ticket8181_PEARL_Pressure_Controller_Add_Purge_Functionality
  base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi
Labels: size/XXL

#1747 CHIPIR snags - xyz table add stop buttons, filters rename to secondary shutter
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_filter_set.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi
Labels: size/L

#1750 fix stop all button in chipir xyz table screen
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi
Labels: size/S

#1748 Ticket6085 add IOC Thorlabs FW102C
  base/uk.ac.stfc.isis.ibex.opis/resources/TPAR_Editor/tpar_editor.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/dds_tensile_stress_rig.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/thorlabsfw102c.opi
Labels: size/XXL
