Repository ISISComputingGroup/ibex_gui, pull requests merged in 2024-03, with the labels that each got.

#1659 Ticket7976 dependency updates
  base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
  base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
  build/copy_in_maven.bat
Labels: size/M

#1685 Fix advanced view toggle bug
  base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/MinimalMotorViewModel.java
Labels: size/S

#1683 Ticket5880_chronus_magnet_status_opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/argus_magnet_status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/chronus_magnet_status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/magnet_status.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L
