Repository ISISComputingGroup/ibex_gui, pull requests merged in 2025-02, with the labels that each got.

#1770 Use PVUtil.getStringArray to get a string array
  base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/ChannelUtilities.py
Labels: size/XS

#1772 hardcode IN:MUONFE:
  base/uk.ac.stfc.isis.ibex.opis/resources/muon_overviews/muon_front_end_overview.opi
Labels: size/XL

#1773 Do not use local PV prefix for trigger PV
  base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/RIKEN_magnet_PSUs.opi
Labels: size/XS

#1775 add muon and epb1 beam current fields to beam status view
  base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS1Observables.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoView.java
  base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/TargetStationOnePanel.java
Labels: size/M

#1771 use RUNDURATION_STR and RUNDURATION_PD_STR
  base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
Labels: size/XS
