Repository ISISComputingGroup/ibex_gui, pull requests merged in 2025-01, with the labels that each got.

#1762 Exclude arm exe from kit
  build/jenkins_build.bat
Labels: size/XS

#1755 Fix for array index out of bounds
  base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupTableViewer.java
Labels: size/XS

#1761 Ticket6090 add ioc litron laser timing control
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1764 Adds opi for L-Dens 3300 density sensor
  base/uk.ac.stfc.isis.ibex.opis/resources/ldens3300.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/L

#1766 Merge issue fixed
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/S

#1765 Add OPI for hifi zero-field system
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/magnetometer_row.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/zero_field_controller_hifi.opi
Labels: size/XXL

#1758 Ticket8332 add litron OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/litron.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
Labels: size/XL

#1767 Dg645 litron timing control fixes (Merge support first)
  base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
Labels: size/L

#1763 Added vertical and horizontal gap limits
  base/uk.ac.stfc.isis.ibex.opis/resources/jaws/Jaws.opi
Labels: size/XXL

#1769 removed final from application.java
  base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/Application.java
Labels: size/XS
