Repository ISISComputingGroup/ibex_gui, pull requests merged in 2025-03, with the labels that each got.

#1777 Don't use excessive CPU in DG645 OPI
  base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.opi
Labels: size/L

#1768 hifi
  base/uk.ac.stfc.isis.ibex.opis/resources/Metrolab_PT2025.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/group3hallprobe.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_control.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_table.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/hifimags.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/zero_field_controller_hifi.opi
Labels: size/XXL

#1778 Hexagon updates
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_energyspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
Labels: size/XXL

#1781 What happens if we enable codeQL on the gui repo?
  .github/workflows/lint.yml
Labels: size/S

#1780 set matplotlib defaults (figure.autolayout, font.size)
  base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java
Labels: size/XS

#1782 Check opis on GHA
  .github/dependabot.yml
  .github/workflows/lint.yml
  base/uk.ac.stfc.isis.ibex.opis/requirements.txt
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_energyspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/LITRON_POWER.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/ldens3300.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
  base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/magnetometer_row.opi
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/requirements.txt
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
  base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py
Labels: size/XXL

#1785 CHIPIR: put filters on collimator screen
  base/uk.ac.stfc.isis.ibex.opis/resources/chipir_collimator/chipircollimator.opi
Labels: size/XXL

#1786 fix axis errors view on inter beckhoff screen
  base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
Labels: size/XS
